-- migrations/002_faecher_lookup.sql
-- NRW Oberstufe – Standardbezeichnungen

INSERT INTO fach_bezeichnungen (kuerzel, bezeichnung) VALUES
('D',   'Deutsch'),
('E',   'Englisch'),
('F',   'Französisch'),
('L',   'Latein'),
('GR',  'Griechisch'),
('SP',  'Spanisch'),
('NL',  'Niederländisch'),
('RU',  'Russisch'),
('IT',  'Italienisch'),
('ZH',  'Chinesisch'),
('M',   'Mathematik'),
('PH',  'Physik'),
('CH',  'Chemie'),
('BI',  'Biologie'),
('IF',  'Informatik'),
('GE',  'Geschichte'),
('EK',  'Erdkunde'),
('SW',  'Sozialwissenschaften'),
('PL',  'Philosophie'),
('PA',  'Pädagogik'),
('KU',  'Kunst'),
('MU',  'Musik'),
('LI',  'Literatur'),
('SPA', 'Sport'),
('ER',  'Evangelische Religionslehre'),
('KR',  'Katholische Religionslehre'),
('PS',  'Psychologie'),
('RK',  'Rechtskunde'),
('WI',  'Wirtschaft'),
('VO',  'Vokalpraktischer Kurs'),
('ZG',  'Zusatzkurs Gesellschaft'),
('ZN',  'Zusatzkurs Naturwissenschaften')
ON DUPLICATE KEY UPDATE bezeichnung = VALUES(bezeichnung);
